enum Tag {
  DESIGN_PATTERNS = 'designpatterns',
  SOFTWARE_DEVELOPMENT = 'softwaredevelopment',
  DISTRIBUTED_SYSTEMS = 'distributedsystems',
  REST = 'rest',
  JSON = 'json',
  HELLO = 'hello',
  DATA_STRUCTURES = 'datastructures',
  ALGORITHMS = 'algorithms',
  BEGINNERS = 'beginners',
  COMMUNITY = 'community',
  OBSERVABILITY = 'observability',
  OBJECT_ORIENTED_PROGRAMMING = 'oop',
  TEST = 'test',
  KOTLIN = 'kotlin',
  JAVA = 'java',
  SPRING = 'spring',
  BEST_PRACTICES = 'bestpractices',
  DATABASE_SYSTEMS = 'databasesystems',
  TOOLS = 'tools',
  CLOUD = 'cloud',
  FUNCTIONAL_PROGRAMMING = 'functionalprogramming',
  CLOJURE = 'clojure',
}

export default Tag
